export const profesiones = [
"Abogado",
"Acompañante Terapéutico",
"Actor",
"Administrador de empresas",
"Administrador Agropecuaria",
"Aerografía",
"Aeronáutica",
"Aerotécnico de la Fuerza Área",
"Agente de seguros",
"Agente de viajes",
"Ing. Agrimensor",
"Lic. Agrónomo",
"Alambrador",
"Albañil",
"Analista de estudio de Mercado. Marketing",
"Analista de sistemas",
"Analista en Administración y Contabilidad",
"Analista en Ingeniería Informática",
"Analista en computación",
"Analista y Programador en videojuegos",
"Anatomopatólogo",
"Animador Social",
"Antropólogo",
"Apicultor",
"Arbitro deportivo",
"Lic. en Archivología",
"Arquitecto",
"Artesano en cuero",
"Artesano de la madera",
"Artesano de tejidos",
"Artes gráficas",
"Lic. en Artes",
"Asistente en Odontología",
"Asistente Veterinario",
"Asistente Veterinario en Equinos",
"Astrónomo",
"Atleta",
"Auxiliar de Enfermería",
"Lic. en Ciencias de la Atmósfera",
"Auxiliar contable",
"Avicultor",
"Ayudante de Arquitecto y de Ingeniero civil.",
"Azafata",
"Bailarín",
"Barman",
"Belleza (técnico en)",
"Bibliotecólogo",
"Biólogo",
"Bioquímico",
"Bombero",
"Botánica",
"Buzo",
"Camarógrafo",
"Cantante",
"Carnicero",
"Carpintero",
"Carpintero de ribera (barcos)",
"Carpintero en Aluminio",
"Cerrajero",
"Lic. en Cartografía",
"Lic. Ciencias Sociales",
"Catadores y clasificadores de alimentos y bebidas",
"Ciencias de la educación",
"Ciencias políticas",
"Clasificador-acondicionador de lanas",
"Cocinero",
"Comercio Exterior",
"Comunicador Social- Organizacional",
"Comunicador Social- Periodista de prensa",
"Comunicador Social- Periodista televisión",
"Comunicador Social- Productor audiovisual",
"Comunicador Social- Publicidad",
"Confitero repostero",
"Constructor",
"Constructor de instrumentos musicales",
"Contador público",
"Controlador de tránsito aéreo",
"Coreógrafo",
"Técnico en Corrección de estilo",
"Corte y confección",
"Cosmetología médica",
"Criador de caballos",
"Crítico de arte",
"Critico periodístico y literario",
"Chacinero o salchichero",
"Chapista",
"Danzas tradicionales",
"Depilación",
"Dentista",
"Despachante de vuelo",
"Despachante de aduana",
"Lic. en Desarrollo",
"Detective",
"Dibujante diseñador",
"Dibujante publicitario",
"Director de cine",
"Director de orquesta",
"Director de coros",
"Lic. en diseñador de paisajes",
"Diseñador gráfico",
"Diseño y decoración de interiores",
"Diseñador industrial",
"Diseñador textil y moda",
"Diseñador web",
"Diseñador de paisajes",
"Dj",
"Demótica",
"Ecologista",
"Economista",
"Economía doméstica",
"Lic. Educación",
"Educación Especial",
"Educación inicial",
"Editor de libros",
"Educador social",
"Educador Sexual",
"Electricista",
"Electricista automotriz",
"Electrotécnico",
"Electroencefalografía y neurofisiología clínica",
"Lic. Enfermería",
"Engarzador de piedras preciosas y semipreciosas",
"Entrenador físico",
"Escultor",
"Escribano público",
"Escritor",
"Expresión corporal",
"Lic. en Estadística",
"Aux. en Farmacia",
"Filósofo",
"Físico",
"Fisioterapeuta",
"Foguista",
"Fonoaudiólogo",
"Tec. Forestación",
"Fotógrafo",
"Gastrónomo",
"Genética",
"Lic. en Geógrafo",
"Geólogo",
"Lic. Gestión Ambiental",
"Gestión Agropecuaria",
"Gestión Cultural",
"Técnico en Gestión de Recursos Naturales y desarrollo sustentable",
"Guardavida",
"Guía turístico",
"Guionista",
"Hemoterapéuta",
"Herrero",
"Higienista en Odontología",
"Historiador",
"Lic. en Ciencias Hídricas Aplicadas",
"Lic. en ciencias Históricas",
"Horticultor",
"Hotelería",
"Importación exportación",
"Industria Frigorífica",
"Ingeniero Alimentario",
"Ingeniero Civil",
"Ingeniero Electricista",
"Ingeniero en Informática o de Sistemas",
"Ingeniero Industrial- Mecánico",
"Ingeniería Industrial.",
"Ingeniero en Telecomunicaciones",
"Ingeniero en Telemática",
"Ingeniero Naval",
"Ingeniero Químico",
"Inseminación Animal",
"Interprete musical",
"Instrumentación Quirúrgica",
"Jardinero",
"Joyero",
"Laboratorista clínico",
"Lechería",
"Lic. En lenguajes y medios audiovisuales",
"Lic. en Letras",
"Lic. en Lingüística",
"Locutor",
"Logística",
"Manicura",
"Maestro",
"Maquetista",
"Maquillaje",
"Marinero",
"Marinero Pescador",
"Marino mercante",
"Marroquinero",
"Masajista",
"Lic. en Matemática",
"Mecánico Industrial",
"Mecánico automotriz",
"Mecánico dental",
"Mecánico de maquinaria agrícola",
"Médico",
"Meteorólogo",
"Microbiología",
"Modista",
"Técnico universitario Museología",
"Lic. en Música",
"Musicoterapeuta",
"Negocios Internacionales",
"Neumocardiólogo",
"Neurofisiología",
"Nutricionista",
"Oceanógrafo",
"Odontólogo",
"Laboratorista en Odontología",
"Oficial de la armada",
"Oficial de la fuerza aérea",
"Oficial del ejército",
"Oficial de la policía",
"Lic. en oftalmología",
"Operador de emisora de radio",
"Operador Inmobiliario",
"Operador PC",
"Operador de refinería (petróleo)",
"Lic. en Obstetricia",
"Óptico",
"Organización de eventos",
"Paleontología",
"Panadero",
"Paracaidismo",
"Partera",
"Patrón de trafico",
"Peletero",
"Periodista deportivo",
"Piloto aviador",
"Piscicultor",
"Podólogo",
"Politólogo",
"Profesor",
"Profesor de Educación física",
"Psicólogo",
"Psicólogo social",
"Psicomotricista",
"Psicopedagogo",
"Pintor de obra",
"Primeros Auxilios",
"Publicista",
"Lic. en Química",
"Técnico Químico",
"Químico Farmacéutico",
"Radio y tv",
"Radiólogo-Imagenología",
"Radioterapista",
"Lic. en Recreación y tiempo libre",
"Refrigeración",
"Registros médicos",
"Relaciones internacionales",
"Recursos humanos y relaciones laborales",
"Lic. en Recursos Naturales",
"Relaciones públicas y organización de eventos",
"Relojero",
"Rematador",
"Restauración de muebles",
"Sacerdote",
"Sanitario",
"Sastre",
"Secretaria Ejecutiva bilingüe",
"Serigrafista",
"Sistema de Seguridad",
"Sociólogo",
"Soldador",
"Sonidista",
"Talabartero",
"Tallado en madera",
"Tallador y pulidor de piedras preciosas y semipreciosas",
"Tapicero",
"Taquígrafo",
"Técnico aeronáutico",
"Técnico agropecuario",
"Técnico en aire acondicionado y refrigeración",
"Técnico en Animación 3D",
"Técnico en Administración y contabilidad (Agroindustrial, Turismo)",
"Técnico Agroenergético",
"Técnico conductor de máquinas a vapor y combustión interna",
"Técnico forestal",
"Técnico en higiene y prevención de accidentes industriales",
"Técnico en educación para la recreación y tiempo libre",
"Técnico en Deportes",
"Tecnólogo mecánico",
"Técnico en promoción de salud y prevención de enfermedades.",
"Técnico en salud ocupacional",
"Técnico en operador de alimentos.",
"Tecnólogo informático",
"Tecnólogo en telecomunicaciones",
"Tecnólogo en cartografía",
"Telefonista",
"Telemarketing",
"Terapeuta ocupacional",
"Teólogo",
"Tornero mecánico",
"Trabajador Social",
"Lic. en traducción literaria",
"Traductor público",
"Lic. en Turismo",
"Vendedor",
"Viticultura y Enología (Licenciado)",
"Visitador medico",
"Veterinario",
"Zapatero"
];
